export const S = {
  placeholder: "想要我做什麼?(例:幫我整理桌面,並且建立資料夾分類)",
  statusReady: (model: string) => `就緒 · ${model}`,
  statusNeedsSetup: "首次使用:送出後將自動安裝必要元件",
  statusDegraded: (d: string) => `注意:${d}`,
  wizardTitle: "首次設定",
  wizardHint: "以下元件將自動安裝(皆免系統管理員權限)",
  wizardSignin: "開啟瀏覽器登入",
  wizardRetry: "重試失敗的步驟",
  wizardInitRetry: "重試",
  wizardDisclaimer: "本工具預設讓 AI 直接執行檔案操作 —— 不逐項確認、也會自動信任工作目錄。想要逐步把關,可在設定開啟「謹慎模式」。",
  wizardStart: "開始使用",
  wizardStepLabels: {
    ollama: "安裝 Ollama(約 1.3GB,視網速可能需要十多分鐘)",
    ollama_upgrade: "升級 Ollama",
    claude: "安裝 Claude Code",
    signin: "登入 ollama.com",
    model: "註冊雲端模型",
  } as Record<string, string>,
  settingsTitle: "設定",
  settingsHotkey: "快捷鍵",
  settingsHotkeyPlaceholder: "Alt+H",
  settingsHotkeyHint: "格式如 Alt+H、Ctrl+Alt+Space。注意:Alt+H 與 Office 功能區快速鍵衝突。",
  settingsModel: "模型",
  settingsCautious: "謹慎模式(危險操作前詢問,取代完全自動)",
  settingsBackground: "背景模式(不開終端機,完成後通知)",
  settingsWorkingDir: "工作目錄",
  settingsWorkingDirPlaceholder: "留空 = 使用者資料夾",
  settingsAutostart: "開機自動啟動",
  settingsSave: "儲存",
  settingsSaved: "已儲存 ✓",
  settingsOpenLogs: "開啟記錄資料夾",
  // ---------- v1.1 ----------
  queueRunning: "進行中",
  queueQueued: "排隊中",
  queueStop: "停止",
  queueCancelTip: "取消此任務",
  queuedToast: "已加入佇列",
  tierFree: "免費",
  tierSubscription: "需訂閱",
  tierUnknown: "未知",
  planFree: "免費方案",
  planPro: "Pro",
  planMax: "Max",
  planTooltip: "查看用量與重置時間",
  micTooltip: () => `語音輸入(說話轉文字)`,
  voiceHint: "語音輸入已啟動,請開始說話",
  attachRemoveTip: "移除這張圖片",
  attachHint: "圖片需搭配支援視覺的模型(如 qwen3-vl:235b-cloud)",
};
