export const S = {
  placeholder: "想要我做什麼?(例:幫我整理桌面,並且建立資料夾分類)",
  statusReady: (model: string) => `就緒 · ${model}`,
  statusNeedsSetup: "首次使用:送出後將自動安裝必要元件",
  statusDegraded: (d: string) => `注意:${d}`,
  wizardTitle: "首次設定",
  wizardHint: "以下元件將自動安裝(皆免系統管理員權限)",
  wizardSignin: "開啟瀏覽器登入",
  wizardRetry: "重試失敗的步驟",
  wizardInitRetry: "重試",
  wizardDisclaimer: "本工具會讓 AI 自動執行檔案操作(預設不逐項確認)。可在設定中開啟「謹慎模式」。",
  wizardStart: "開始使用",
  wizardStepLabels: {
    ollama: "安裝 Ollama",
    ollama_upgrade: "升級 Ollama",
    claude: "安裝 Claude Code",
    signin: "登入 ollama.com",
    model: "註冊雲端模型",
  } as Record<string, string>,
  settingsTitle: "設定",
  settingsHotkey: "快捷鍵",
  settingsHotkeyPlaceholder: "Alt+H",
  settingsHotkeyHint: "格式如 Alt+H、Ctrl+Alt+Space。注意:Alt+H 與 Office 功能區快速鍵衝突。",
  settingsModel: "模型",
  settingsCautious: "謹慎模式(危險操作前詢問,取代完全自動)",
  settingsBackground: "背景模式(不開終端機,完成後通知)",
  settingsWorkingDir: "工作目錄",
  settingsWorkingDirPlaceholder: "留空 = 使用者資料夾",
  settingsAutostart: "開機自動啟動",
  settingsSave: "儲存",
  settingsSaved: "已儲存 ✓",
  settingsOpenLogs: "開啟記錄資料夾",
};
